fixtures:
  forge_modules:
    apt:
      repo: "puppetlabs/apt"
      ref: "2.2.0"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.2.0"
    concat:
      repo: "puppetlabs/concat"
  symlinks:
    curator: "#{source_dir}"
